name: Mocha

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # You can specify the Node.js version you use

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install mocha and chai as dev dependencies
      - name: Install Mocha and Chai
        run: npm install --save-dev mocha chai nyc coveralls

      # Run tests
      - name: Run tests
        run: npm test test/*

      # Upload coverage report to Coveralls
      - name: Upload coverage to Coveralls
        run: nyc report --reporter=text-lcov | coveralls
