name: tests-coverage

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # You can specify the Node.js version you use

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Run tests
      - name: Run tests
        run: npm test test/*

      # Save coverage report in Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}



